# Generated by Django 2.2.6 on 2020-03-18 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_addedtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('module_number', models.IntegerField(blank=True, default=0, null=True)),
                ('file1', models.FileField(blank=True, upload_to='')),
                ('file2', models.FileField(blank=True, upload_to='')),
                ('file3', models.FileField(blank=True, upload_to='')),
                ('file4', models.FileField(blank=True, upload_to='')),
                ('file5', models.FileField(blank=True, upload_to='')),
                ('file6', models.FileField(blank=True, upload_to='')),
                ('process_name', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('module_addedtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.TextField(blank=True, default=None, null=True)),
                ('option1', models.TextField(blank=True, default=None, null=True)),
                ('option2', models.TextField(blank=True, default=None, null=True)),
                ('option3', models.TextField(blank=True, default=None, null=True)),
                ('option4', models.TextField(blank=True, default=None, null=True)),
                ('correct_option', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(blank=True, max_length=500, null=True)),
                ('scenario_desc', models.TextField(blank=True, default=None, null=True)),
                ('option1', models.TextField(blank=True, default=None, null=True)),
                ('option2', models.TextField(blank=True, default=None, null=True)),
                ('option3', models.TextField(blank=True, default=None, null=True)),
                ('option4', models.TextField(blank=True, default=None, null=True)),
                ('correctoption', models.TextField(blank=True, default=None, null=True)),
                ('associated_module', models.CharField(blank=True, max_length=500, null=True)),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                ('scenario_file', models.FileField(blank=True, null=True, upload_to='')),
                ('scenario_addedtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_module', models.IntegerField(blank=True, null=True)),
                ('sequence_num', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=500, null=True)),
                ('course_team', models.CharField(blank=True, max_length=500, null=True)),
                ('course_createdtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('course_status', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('test_time', models.IntegerField(blank=True, default=30, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminboard.Module')),
            ],
        ),
    ]
