# Generated by Django 2.2.6 on 2020-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0001_initial_manual1'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_cover',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
