# Generated by Django 2.2.6 on 2020-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0002_course_course_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='module',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='module',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='module',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='module',
            name='file6',
        ),
        migrations.AddField(
            model_name='module',
            name='link1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='link9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
