# Generated by Django 2.2.6 on 2020-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0003_auto_20200624_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='process_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
