# Generated by Django 2.2.6 on 2020-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0006_auto_20200703_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
