# Generated by Django 2.2.6 on 2020-07-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0007_module_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_name',
        ),
    ]
