# Generated by Django 2.2.6 on 2020-07-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0008_remove_scenario_scenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_questcount',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
