# Generated by Django 2.2.6 on 2020-11-06 13:33

import adminboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0010_auto_20200810_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(blank=True, default=adminboard.models.IST_datetime, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_time',
            field=models.DateTimeField(blank=True, default=adminboard.models.IST_datetime, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='quest_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_createdtime',
            field=models.DateTimeField(blank=True, default=adminboard.models.IST_datetime, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_addedtime',
            field=models.DateTimeField(blank=True, default=adminboard.models.IST_datetime, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_addedtime',
            field=models.DateTimeField(blank=True, default=adminboard.models.IST_datetime, null=True),
        ),
    ]
