# Generated by Django 2.2.6 on 2020-07-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='revoke_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
