# Generated by Django 2.2.6 on 2020-07-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_progress_revoke_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='revoke_status',
        ),
    ]
