# Generated by Django 2.2.6 on 2020-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_progress_revoke_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempted',
            name='option_given',
            field=models.TextField(default=None, null=True),
        ),
    ]
