# Generated by Django 2.2.6 on 2020-08-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200729_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='rating_flag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
