# Generated by Django 2.2.6 on 2020-11-25 10:52

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201106_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_email', models.EmailField(blank=True, default=None, max_length=254)),
                ('report_title', models.CharField(blank=True, max_length=500, null=True)),
                ('report_description', models.TextField(blank=True, default=None, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='')),
                ('submit_time', models.DateTimeField(blank=True, default=employee.models.IST_datetime, null=True)),
            ],
        ),
    ]
