# Generated by Django 2.2.6 on 2020-12-02 06:01

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_reportissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('contributor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contributor_team', models.CharField(blank=True, max_length=500, null=True)),
                ('submission_date', models.DateTimeField(blank=True, default=employee.models.IST_datetime, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('process_name', models.CharField(blank=True, max_length=3000, null=True)),
                ('case_study', models.FileField(blank=True, null=True, upload_to='')),
                ('supporting_docs', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RaiseTechIssue',
        ),
    ]
