# Generated by Django 2.2.6 on 2021-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20201202_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
