# Generated by Django 2.2.6 on 2021-03-17 07:56

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_contribution_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=200)),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('rejected_remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=employee.models.IST_datetime)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Progress')),
            ],
        ),
    ]
